[package]
name = "stun-zc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3.2"
eyre = "0.6.8"
hmac = "0.12.1"
md5 = "0.7.0"
sha1 = "0.10.5"
